# Generated by Django 5.2.4 on 2025-09-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicetype_alter_user_role_servicestation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationService',
        ),
    ]
