# Generated by Django 5.2.4 on 2025-09-19 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_stationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicetype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.servicestation')),
            ],
            options={
                'unique_together': {('station', 'service_type')},
            },
        ),
    ]
