# Generated by Django 5.2.4 on 2026-01-10 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_stationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlots',
            fields=[
                ('AppointmentSlotsID', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDay', models.CharField(max_length=20)),
                ('AppointmentTime', models.TimeField()),
                ('MaxAppointments', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('AppointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment')),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('UpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
