# Generated by Django 5.2.4 on 2026-01-10 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appointmentslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslots',
            name='AppointmentID',
        ),
        migrations.AddField(
            model_name='appointment',
            name='AppointSlotID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.appointmentslots'),
        ),
    ]
