# Generated by Django 5.2.4 on 2026-01-10 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_appointmentslots_appointmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslots',
            name='UpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
