# Generated by Django 5.2.4 on 2026-01-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepairOrder', '0005_remove_jobcard_createdbyuser_and_more'),
        ('accounts', '0007_alter_appointmentslots_updatedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='VehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RepairOrder.vehicle'),
        ),
    ]
