# Generated by Django 5.2.4 on 2026-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appointmentslots_vehicleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
