# Generated by Django 5.2.4 on 2026-01-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepairOrder', '0005_remove_jobcard_createdbyuser_and_more'),
        ('accounts', '0009_appointment_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='VehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_vehicle', to='RepairOrder.vehicle'),
        ),
    ]
