# Generated by Django 5.2.4 on 2026-02-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appointment_vehicleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('ServiceStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.servicestation')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('UserRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('AssignedOn', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roles')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
